### ISSUE TITLE
'default_app_config' is deprecated in Django 3.2.X

### ISSUE THREAD

**Issue by nickgashkov** [timmyomahony/django-pagedown#100]
Hello, thank you for your project! 

After upgrading to Django 3.2, there's a new deprecation warning, related to `default_app_config` in `__init__.py`:

```
  /Users/.../lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'pagedown' defines default_app_config = 'pagedown.apps.PagedownConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)
```

Looks like Django will be removing this option in Django 4.1 — [ref.](https://docs.djangoproject.com/en/3.2/releases/3.2/#id3)

**Comment by timmyomahony** [comment]
Thanks for the issue, I'll have a look into it.

**Comment by timmyomahony** [comment]
Added a fix for this:

https://github.com/timmyomahony/django-pagedown/commit/26fdf0452dbedd5c10e0d2cb6d34e66abd83b413

Will be included in the next release.
