### ISSUE TITLE
I get a: ModuleNotFoundError: No module named 'pagedown.urls'

### ISSUE THREAD

**Issue by tetrahed** [timmyomahony/django-pagedown#101]
Whenever I tried adding `path('', include('pagedown.urls')),` to `urlpatterns` in urls.py, I simply get a `ModuleNotFoundError: No module named 'pagedown.urls'`.

**Comment by timmyomahony** [comment]
How have you installed the library? Have you added it to your `INSTALLLED_APPS`?

**Comment by timmyomahony** [comment]
I'm going to close this issue. If you're still having an issue please leave a comment or open another issue
