### ISSUE TITLE
Can you add a feature so LaTeX/MathJax renders in the preview?

### ISSUE THREAD

**Issue by stampthemail222** [timmyomahony/django-pagedown#102]
Can you make the library so that MathJax or LaTeX dynamically renders automatically?

**Comment by timmyomahony** [comment]
Unfortunately that's down to [the underlying `pagedown` library](https://github.com/StackExchange/pagedown). There's an outstanding issue for MathJax support

https://github.com/StackExchange/pagedown/issues/85

but it doens't seem to be implemented.
