### ISSUE TITLE
Markdown rendering inaccuracy

### ISSUE THREAD

**Issue by moaxey** [timmyomahony/django-pagedown#16]
My clients got confused as the preview rendered headings which were not correctly formatted.

The markdown spec requires a space after the ## but the preview renders them as headings without the space, but on my live pages (rendered through markdown-deux) they appeared as normal paragraphs with hash marks visible.

Is this coming from the javascript dependency?

**Comment by Pawamoy** [comment]
I think it is because pagedown uses StackOverflow's spec and markdown-deux uses another...

Not practical then, since previews differ from rendered HTML :sad:
