### ISSUE TITLE
How to render markdown without preview?

### ISSUE THREAD

**Issue by will-emmerson** [timmyomahony/django-pagedown#18]
I just want to render the markdown to html in a template, without the preview.

**Comment by hitarths** [comment]
There is a difference between the django-pagedown preview and the html generated by the django-markdown-deux. Specifically the preview from pagedown shows line breaks when I press enter, but when I render it using the deux tag, the line breaks are gone. BUT, it I put two line breaks, then deux DOES puts <br/> tags.
I am not sure if its a bug in pagedown, or its just the fact that I am silly!

**Comment by timmyomahony** [comment]
@hitarths that's interesting, I haven't noticed that before. The `django-markdown-deux` library uses `python-markdown2` behind the scenes. This library (`python-markdown2`) allows [configuration via "Extras".](https://github.com/trentm/python-markdown2/wiki/Extras#implemented-extras) I notice a `break-on-newline` option there. Something like this might work (I haven't tested it though):

```
MARKDOWN_DEUX_STYLES = {
    "default": {
        "extras": {
            "break-on-newline": None,
        },
        # ...
    },
}
```
