### ISSUE TITLE
PAGEDOWN_DEFAULT_TEMPLATE not Working

### ISSUE THREAD

**Issue by DaWy** [timmyomahony/django-pagedown#37]
I've set up the constant in my settings.py but template is not loading... Any hints on this?

`PAGEDOWN_DEFAULT_TEMPLATE = PROJECT_ROOT + "/templates/pagedown.html"`

**Comment by cyberthrone3** [comment]
Dawy, use PAGEDOWN_WIDGET_TEMPLATE instead.

**Comment by timmyomahony** [comment]
Apologies, I'm very late to this. I've update the readme with the correct variable name. Thanks
