### ISSUE TITLE
How to make markdown preview side by side (on the same line)?

### ISSUE THREAD

**Issue by johnsmeeth** [timmyomahony/django-pagedown#38]
Hello friend.
In admin how to make markdown preview side by side (on the same line) with that field.
Many thanks.,

**Comment by jnns** [comment]
This is not a question belonging into the issue tracker but rather on StackOverflow. 

But anyway, you can adjust the CSS used to style the pagedown textarea and its preview (see [README](https://github.com/timmyomahony/django-pagedown#customizing-the-css)). Just make `.wmd-wrapper` use `display: flex` and play around with margins and the like.

**Comment by timmyomahony** [comment]
Thanks @jnns
