### ISSUE TITLE
Having Trouble Running 'django-pagedown' with Python 3.4

### ISSUE THREAD

**Issue by nicorellius** [timmyomahony/django-pagedown#39]
Great app, I just hope I can get it to work. It'd be nice to see all the requirements on the github page, BTW... (Python support?)

I'm running Django 1.9 with Python 3.4. I installed django-pagedown, and started editing a textarea in the Django admin. The preview worked, and showed the rendering correctly. At this time, the result on the web page didn't have the correct rendering.

I then installed django-markdown-deux, and got it to work on the web page. But then, after trying to save the textarea in the Django admin, I got weird error. The field showed some CSS and replaced what was in there. No matter what I put in the field, this same CSS appeared and the field wouldn't validate.

I then uninstalled django-markdown-deux, and now I can't get django-pagedown to work correctly. Not sure if this is a bug or something I'm doing wrong. Any ideas?

**Comment by nicorellius** [comment]
My apologies... I have partially fixed my issue. In the default template, this line caused an inspection error in my IDE:

`<textarea{{ attrs|safe }}>{{ body }}</textarea>`

...and so stupidly, I closed the first textarea and this was causing the CSS injection bug.

Now, it's mostly working, but the paragraph elements are appearing in the rendered page. I'm working on this. Sorry to waste your time.

**Comment by timmyomahony** [comment]
Did you get everything fixed?

**Comment by nicorellius** [comment]
Yes, thank you... I just had to tweak the sanitation (raw HTML) settings to allow my HTML that I wanted. You mention rendering markdown in your template, using `django-markdown-deux`. This was nicely documented in the docs... Thanks for the follow up -- great application!
