### ISSUE TITLE
 RemovedInDjango110Warning: render() must be called with a dict, not a Context.

### ISSUE THREAD

**Issue by sobolevn** [timmyomahony/django-pagedown#42]
> .virtualenv/lib/python2.7/site-packages/pagedown/widgets.py:55: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
>   return template.render(context)

Here's the part with the warning:

       context = Context({
            "attrs": flatatt(final_attrs),
            "body": conditional_escape(force_unicode(value)),
            "id": final_attrs["id"],
            "show_preview": self.show_preview,
        })
        return template.render(context)

https://github.com/timmyomahony/django-pagedown/blob/master/pagedown/widgets.py#L49

I will do a PR with a fix for this issue.

**Comment by timmyomahony** [comment]
Hey, as mentioned in the PR, I'll check this out. Thanks!
