### ISSUE TITLE
Fenced code blocks do not receive pre tag

### ISSUE THREAD

**Issue by contstantine** [timmyomahony/django-pagedown#44]
Suppose I have a database entry where I have the following "code block"

(triple back tick)
some fenced code block
another line
(triple back tick)

I also have the following model method in django `models.py`

```
def get_markdown(self):
    	return mark_safe(markdown(self.body))
```

... where `body = models.TextField()`
Then the result being returned by the method is the following html code...

```
<p><code>
some fenced code block
another line
</code></p>
```

The `<pre>` tag is missing and it also displays inline rather than receiving the line break.

**Comment by timmyomahony** [comment]
Hey, I have a feeling that this may be an issue with the underlying 'pagedown' library created by StackOverflow. I'll check it out and get back to you

**Comment by contstantine** [comment]
Thank you for the prompt response

**Comment by contstantine** [comment]
It was indeed an outside issue. More specifically, it was an issue `django-markdown-deux`

I have resolved the issue... more details here [https://github.com/trentm/django-markdown-deux/issues/20](https://github.com/trentm/django-markdown-deux/issues/20)
