### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attachEvent' of null

### ISSUE THREAD

**Issue by fubel** [timmyomahony/django-pagedown#48]
I installed django-pagedown and followed the instructions for usage outside the Django admin. However, with the given template

```
<html>
    <head>
        {{ form.media }}
    </head>
    <body>
        <form>
            {{ form }}
        </form>
    </body>
</html>
```

the pagedown editor does not render. The static files generated by `form.media` are 

```
<script type="text/javascript" src="/static/pagedown/Markdown.Converter.js"></script>
<script type="text/javascript" src="/static/pagedown-extra/pagedown/Markdown.Converter.js"></script>
<script type="text/javascript" src="/static/pagedown/Markdown.Sanitizer.js"></script>
<script type="text/javascript" src="/static/pagedown/Markdown.Editor.js"></script>
<script type="text/javascript" src="/static/pagedown-extra/Markdown.Extra.js"></script>
<script type="text/javascript" src="/static/pagedown_init.js"></script>
```
 
and are reachable. Inspecting via Chrome yiels

> Markdown.Editor.js:324 Uncaught TypeError: Cannot read property 'attachEvent' of null

The preview text-areas are rendered correctly. Any suggestions?

**Comment by timmyomahony** [comment]
Thanks @fubel I'll have to check this out and see if I cam replicate it

**Comment by timmyomahony** [comment]
Hey, I was never able to replicate this. Do you remember if you got it working in the end? I've added an example application to the repo with forms working outside of the admin that might be of help

**Comment by fubel** [comment]
Thank you, I will check out your example application! :)

**Comment by timmyomahony** [comment]
I'm closing this issue. Please let me know if there's any further issue and I'll reopen it
