### ISSUE TITLE
Widget attachable to multiple instances of the same form?

### ISSUE THREAD

**Issue by Yobmod** [timmyomahony/django-pagedown#49]
Is it possible to have the widget attached to multiple instances of the same form on a page?
When i try i get:

`I get: Pagedown editor already attached to element: <#id_text>. `

Can the id be specified so it attaches to all instances? 
eg. to comments and replies in a thread. 
Or do i have to make seperate forms?

**Comment by timmyomahony** [comment]
Apologies for the late reply. I'm not sure if I'm understanding correctly, but if you are rendering your form more than once on the same page it will be sharing the `id` and `name` which isn't a good idea. You could use a `Formset` instead?

**Comment by timmyomahony** [comment]
I'm going to close this issue now. Please let me know if you want it reopened
