### ISSUE TITLE
Problem with Django v1.11

### ISSUE THREAD

**Issue by DelahayeYourself** [timmyomahony/django-pagedown#51]
Hello,

There is some import error when using django-pagedown with the version 1.11 of Django:

 File "/usr/lib/python2.7/site-packages/pagedown/widgets.py", line 3, in <module>
    from django.forms.widgets import flatatt

ImportError: cannot import name flatatt

Some changes occured in django maybe ?

**Comment by timmyomahony** [comment]
Fixed with #50
