### ISSUE TITLE
load markdown_deux_tags not working in django 1.11

### ISSUE THREAD

**Issue by jtank38** [timmyomahony/django-pagedown#55]
I've followed the instructions given in the doc to render the markdown into my template.
Here's my code 
```
{% include "Home/includes/snippets_navbar.html" %}
{% load markdown_deux_tags %}


{%  block content  %}

<h3>{{post.title}}</h3>
	<h6>{{post.date}}</h6>
	{{post.body|markdown}}
{% endblock %}



```
And It's not responding at all

**Comment by jtank38** [comment]
ok I solved it another way, using mark_safe and after making an instance of markdown_deux in models.py and referencing it on my template.
Models.py
```from __future__ import unicode_literals
from pagedown.widgets import AdminPagedownWidget
from django.db import models
from markdown_deux import markdown
from django.utils.safestring import mark_safe
class Post(models.Model):
    title= models.CharField(max_length=140)
    body=models.TextField()
    date=models.DateTimeField()


    def get_markdown(self):
        body = self.body
        markdown_text= markdown(body)
        return mark_safe(markdown_text)
```
However if anyone can tell me why the above one is not working I'd really appreciate that

**Comment by timmyomahony** [comment]
Hey, this sounds like it was an issue with `mardkwon_deux_tags` and not this plugin? Let me know otherwise and glad you got it sorted.
