### ISSUE TITLE
have way to describe code language?

### ISSUE THREAD

**Issue by Megido6** [timmyomahony/django-pagedown#56]
for example 
i insert json fragment to content

i use pygments  for code lang detection and colorize. 
but code lang mostly undetected if code is short or it's not code like this json data
```
{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}
```
secondly if i manually add 
```json
[
  {"foo": "bar"}
]
```

i see pretty colorized json

I do not find it very difficult to arrange backticks, but if there is another solution, please tell me

**Comment by timmyomahony** [comment]
Do you mean in the preview box below the text input or when you actually render the markdown content on your page? This sounds like an issue with the rendering, not the plugin itself.

**Comment by timmyomahony** [comment]
I'm going to close this for the moment as I don't think it's an issue with the plugin
