### ISSUE TITLE
Django 1.8 Admin Form CSS Conflict

### ISSUE THREAD

**Issue by FrankSalad** [timmyomahony/django-pagedown#60]
Opening this just to note that I had an issue dropping this into an existing Django 1.8.18 project. 

<img width="657" alt="screen shot 2017-10-24 at 2 05 59 pm" src="https://user-images.githubusercontent.com/2359644/31968059-ba51a006-b8c4-11e7-9682-6c645c39d93c.png">

See how the first scooby line is really indented in the preview? 
Looks like the [model admin css ](https://github.com/django/django/blob/1.8.18/django/contrib/admin/static/admin/css/forms.css#L85) is providing markup that is adding padding and margin to `<p>` elements created by the editor under the `form .aligned p` selector.

This selector was removed in a later commit - the current version of Django doesn't have it.

**Comment by timmyomahony** [comment]
Thanks! I'll check this out

**Comment by timmyomahony** [comment]
Pulling this in now
