### ISSUE TITLE
Does this support Python 3?

### ISSUE THREAD

**Issue by Flimm** [timmyomahony/django-pagedown#67]
There are no indications that this package supports Python 3. There a missing classifiers in `setup.py`. Without these classifiers, sites like this cannot detect that this package supports Python 3:

https://djangopackages.org/packages/p/django-pagedown/

**Comment by timmyomahony** [comment]
Thansk Flimm. I've added some classifiers now. Here are some links for future reference:

- https://pypi.org/classifiers/
- https://packaging.python.org/guides/distributing-packages-using-setuptools/#classifiers

**Comment by Flimm** [comment]
Thanks!
