### ISSUE TITLE
pip install django-pagedown not working fine.

### ISSUE THREAD

**Issue by MonarchChakri** [timmyomahony/django-pagedown#69]
pip install django-pagedown is actually downloading the wrong code which is causing some render errors.
![github_django_pagedown](https://user-images.githubusercontent.com/23417550/42164507-dcbf21f2-7e23-11e8-8be2-77d79a41a3a8.png)
![git_hub_default_html](https://user-images.githubusercontent.com/23417550/42164664-57237bb4-7e24-11e8-91da-07daae571407.png)

**Comment by MonarchChakri** [comment]
I fixed the issue man! it was not due to the html. I have actually read the code and found that you have forgot to add the parameter renderer to the render function of pagedownwidget.
![github](https://user-images.githubusercontent.com/23417550/42172012-700bb178-7e38-11e8-8ccf-4a17f3bbf4c6.png)
Give me permission to edit it.

**Comment by MonarchChakri** [comment]
Close this issue once you have accepted my pull request.

**Comment by timmyomahony** [comment]
@MonarchChakri thanks for this and apologies for the delay in replying. I'll check it out.

**Comment by timmyomahony** [comment]
Should be fixed as of `1.0.6`
