### ISSUE TITLE
content = forms.TextField(widget=PagedownWidget()) Doesn't work on Djnago 2.0

### ISSUE THREAD

**Issue by iocohen** [timmyomahony/django-pagedown#74]
# content = forms.TextField(widget=PagedownWidget())

This code doesnt work. why?

from django import forms
from pagedown.widgets import PagedownWidget
from .models import Blog_Post

class PostForm(forms.ModelForm):
    
 	# content = forms.TextField(widget=PagedownWidget())
    class Meta:
        model=Blog_Post
        fields = [
            "title",
            "image",
            "location",
            "content",
            "draft",          

        ]

**Comment by iocohen** [comment]
pip install  it, using django version. i run my site on production and when i uncomment that content TextField destrois my site.

**Comment by iocohen** [comment]
i think was 1.14 or something like this when i installed it

**Comment by iocohen** [comment]
this is the code from my models.py


class Blog_Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, default=1, on_delete=True)
    title = models.CharField(max_length=120,blank=True, null=True)
    slug = models.SlugField(unique=True)
    image = models.ImageField(null=True, blank=True,
                              width_field="width_field",
                              height_field="height_field",
			      upload_to='blog_post_images',
	)
    height_field=models.IntegerField(default=140,blank=True, null=True)
    width_field = models.IntegerField(default=360,blank=True, null=True)
    content=models.TextField(blank=True, null=True)
    draft = models.BooleanField(default=False,blank=True)
    publish = models.DateField(auto_now=False, auto_now_add=False,blank=True, null=True)
    location =models.CharField(max_length=120, default="", blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False,blank=True, null=True)
    timestamp=models.DateTimeField(auto_now=False, auto_now_add=True,blank=True, null=True)

    objects =PostManager()

    def __str__(self):
        return self.title + " | " + self.location

    # def get_absolute_url(self):
    #     return reverse("posts:detail", kwargs={"id":self.id})

    class Meta:
        ordering = ["-timestamp", "-updated"]


    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"slug": self.slug})

**Comment by timmyomahony** [comment]
What error is being thrown?

**Comment by iocohen** [comment]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.7 (Ubuntu) Server at cohen.ro Port 80

**Comment by timmyomahony** [comment]
That's not the server error message, that's the _browser_ error message. The error message will be in your server logs. 

What I imagine is the problem, is that you are trying to use `TextField` in your form, which isn't a form field, it's a model field. You need: `content = forms.CharField(widget=PagedownWidget())`
