### ISSUE TITLE
Space before URL results in malformed URL in markdown

### ISSUE THREAD

**Issue by pmac** [timmyomahony/django-pagedown#75]
See the [screenshot attached to the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1507823) we received. Basically it seems that what is happening is that if you click the globe icon to insert a link and your URL in the field has a space before it (which is hard to see) then the result will have `http://%20` prepended to it. That is if you paste ` https://example.com` into the field, then what is inserted into the document is `http://%20https://example.com`.

**Comment by timmyomahony** [comment]
Thanks for the feedback. My gut feeling is that this is an issue with the underlying Pagedown library. The library uses a pretty old fork of the page Pagedown library, so maybe it's time for an upgrade to a more recent version. I'll look into it

**Comment by timmyomahony** [comment]
Should be fixed with version 2.0.3

**Comment by pmac** [comment]
This is still an issue with the latest version.
