### ISSUE TITLE
Django 2.2 requires jquery to be set as dependency

### ISSUE THREAD

**Issue by kaduuuken** [timmyomahony/django-pagedown#76]
see https://docs.djangoproject.com/en/2.2/releases/2.2/#merging-of-form-media-assets

`compatible_staticpath('admin/js/jquery.init.js'),` needs to be added to `AdminPagedownWidget` in line 93 and to `PagedownWidget` in line 39 in `widgets.py`

**Comment by timmyomahony** [comment]
Should be fixed with version `2.0.3`
