### ISSUE TITLE
Where do you put the widget customization?

### ISSUE THREAD

**Issue by tetrahed** [timmyomahony/django-pagedown#81]
If we would like to customize Pagedown, where in our project do we extend the widget? Which file does the code down below belong?

from pagedown.widgets import PagedownWidget

class MyNewWidget(PagedownWidget):
    template_name = '/custom/template.html'

    class Media:
        css = {
            'all': ('custom/stylesheets.css,)
        }
        js = ('custom/javascript.js',)

**Comment by timmyomahony** [comment]
You place that in your own app within a `widget.py` file. You then use reference that widget in a custom `Form`. If you want to use the widget in the admin, then you need to reference that _form_ in your `admin.py`. Similarly if you want to use it in an app.
