### ISSUE TITLE
Collectstatic pulling in demo project css

### ISSUE THREAD

**Issue by peteretep** [timmyomahony/django-pagedown#84]
I have installed the package as described and want to use my own form.
The form seems to be using the css in demo.css, messing up the colours. 
Not sure why. I can delete this file, but when I run collectstatic it returns. 

![image](https://user-images.githubusercontent.com/1403113/74455904-f0706e00-4e7d-11ea-8560-4964b8829882.png)

**Comment by timmyomahony** [comment]
Hi Peter. `demo.css` is included with the widget as it's the default stylesheet for the Pagedown editor:

https://github.com/timmyomahony/django-pagedown/blob/master/pagedown/widgets.py#L16

If it wasn't included you'd get a completely unstyled widget. You can either provide your own overwritten `pagedown/demo/browser/demo.css` file in your static folder, or you can overwrite the widget entirely and remove the `demo.css` media file. Something like:

```sh
from pagedown.widgets import PagedownWidget

class MyCustomPagedownWidget(PagedownWidget):
    
    class Media:
        js = ('pagedown/Markdown.Converter.js',
              'pagedown-extra/pagedown/Markdown.Converter.js',
              'pagedown/Markdown.Sanitizer.js',
              'pagedown/Markdown.Editor.js',
              'pagedown-extra/Markdown.Extra.js',
              'pagedown_init.js')
```

**Comment by peteretep** [comment]
thanks for that clarification
