### ISSUE TITLE
Collect Static does not collect pagedown.css

### ISSUE THREAD

**Issue by theRealBithive** [timmyomahony/django-pagedown#88]
Somehow pagedown.css isn't collected by collectstatic and thus is missing in my template.

**Comment by timmyomahony** [comment]
😬 I just realised that the `pagedown.css` wasn't in the `MANIFEST.in` file which _may_ be the reason for this. 

I've added a fix in the `master` branchbut can't test/release just at the moment (will be able to later).

**Comment by theRealBithive** [comment]
I added the file to my static folder by hand - so don't hurry.

**Comment by timmyomahony** [comment]
Ok thanks. It's probably affecting all installs though so I'll test it out asap. Thanks for reporting.

**Comment by timmyomahony** [comment]
Just pushed `2.1.2` that hopefully fixes the issue
